name: M1MIASHS-NLP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - nbstripout
  - pandas
  - jinja2
  - numpy
  - scikit-learn
  - statsmodels
  - scapy
  - nltk
  - matplotlib
  - seaborn
  - mystmd
  - pip